---
title: "invertsuiker"
description: |
  Hoe je invertsuiker kunt maken.
author:
  - name: Ben Welman
date: 01-06-2019
preview: invertsuiker.jpg
categories:
  - suiker
output:
  distill::distill_article
---

Bij het maken van likeuren wordt vaak invertsuiker gebruikt omdat deze wat zoeter is dan gewone suiker, waardoor je minder nodig hebt. Ook wordt het gebruikt bij het maken van stookwijn omdat de vergisting wat sneller verloopt. En een enkele keer zie ik wel eens dat een hobbybrouwer het om dezelefde reden gebruikt als bottelsuiker. Ik zelf heb het alleen nog maar gebruikt bij het maken van limoncello en kruidenbitter.

Invertsuiker is een mengsel van gelijke hoeveelheden glucose (druivensuiker) en fructose (vruchtensuiker) en wordt gemaakt uit sacharose (gewone kristalsuiker) door de inwerking van zuren en het enzym sacharase (invertase). Honing is voor het grootste deel invertsuiker. Invertsuiker heeft een aantal voordelen t.o.v. gewone suiker:

-  Heeft meer zoetkracht (fructose is bijna twee keer zo zoet als saccharose).
-  Kristalliseert minder snel en blijft daardoor zachter.
-  Smaak is aangenamer en fijner.
-  Oplosbaarheid in alcohol is groter.
-  Wordt sneller door gist in alcohol omgezet.

Om invertsuiker uit gewone suiker te maken moet het saccharosemolekuul (glucose~fructose) gesplitst worden in glucose en fructose. Deze splitsing (hydrolyse) verloopt het beste bij kooktemperatuur in een licht zuur milieu. Het licht zure milieu kun je krijgen door wat citroenzuur (of eventueel citroensap) aan het water toe te voegen.

Recept

-  1 kg kristalsuiker
-  0,5 liter water
-  1 gram citroenzuur (of sap van 1 citroen)

Het water verwarmen en het citroenzuur hierin oplossen. Wanneer het water tegen de kook aan is, de suiker langzaam onder roeren hierin oplossen. Ongeveer 15-20 min. laten koken, dan is alle kristalsuiker omgezet in invertsuiker. Daarna afkoelen. Je hebt dan een (invert)suikersiroop gekregen.

Het kan zijn dat tijdens het koken bruin schuim gevormd wordt. Dit komt door verontreinigingen bij de fabricage van suiker. Dit schuim kun je het beste afscheppen. Eigen gemaakte invertsuikersiroop heeft vaak een lichtgele kleur wat de kwaliteit niet verminderd.

Hoewel de eigen gemaakte invertsuikersiroop goed houdbaar is kun je deze het beste toch maar zo snel mogelijk gebruiken omdat de suiker snel kan uitkristalliseren.
